
home-dir = /home/ubuntu/debianadmin

// ctu's (Convert To Uppaal) paths and files
ctu.path = ${home-dir}/ctu
ctu.path.cons = ${home-dir}/tmp/cons/OcamlContracts_
ctu.path.nets = ${home-dir}/tmp/nets/OcamlNetworks_
ctu.path.automata = ${home-dir}/tmp/nets/OcamlAutomata_
ctu.path.labels = ${home-dir}/tmp/nets/OcamlLabels_

ctu.param.translate = -s
ctu.param.binding = -v
ctu.param.culpable = -ic
ctu.param.duty = -id
ctu.param.start = -start
ctu.param.step = -step
ctu.param.admit-compliant = -da
ctu.param.kind-of = -dk
ctu.param.dual-of = -dd
ctu.param.build-automaton = -ba
ctu.param.get-labels = -gl
ctu.param.to-string = --to-string

// Uppaal's paths and files
uppaal.path = ${home-dir}/uppaal/bin-Linux/verifyta 
uppaal.params =  ${home-dir}/uppaal/bin-Linux/test-compliance.q // | grep -e '--' | cut -d'-' -f 3 // do not remove the initial space

// Xmllint's path and files
validator.path = xmllint --schema 
validator.path.schema = ${home-dir}/validator-sources/ContractSchema.xsd
validator.path.files = ${home-dir}/tmp/validatorFiles/
validator.file-prefix = ValidatorInput_

