
base-dir = /home/ubuntu/debianadmin
tmp-dir = ${sys:java.io.tmpdir}/middleware

// ctu's (Convert To Uppaal) paths and files
ctu.exec = 			${base-dir}/ctu
ctu.path.cons = 	${tmp-dir}/OcamlContracts_
ctu.path.nets = 	${tmp-dir}/OcamlNetworks_
ctu.path.automata = ${tmp-dir}/OcamlAutomata_
ctu.path.labels = 	${tmp-dir}/OcamlLabels_

ctu.param.translate = 		-s
ctu.param.binding = 		-v
ctu.param.culpable = 		-ic
ctu.param.duty = 			-id
ctu.param.start = 			-start
ctu.param.step = 			-step
ctu.param.admit-compliant = -da
ctu.param.kind-of = 		-dk
ctu.param.dual-of = 		-dd
ctu.param.build-automaton = -ba
ctu.param.get-labels = 		-gl
ctu.param.to-string = 		--to-string

// Uppaal's paths and files
uppaal.exec = 	${base-dir}/uppaal/bin-Linux/verifyta 
uppaal.params = ${base-dir}/uppaal/bin-Linux/test_compliance.q

// Xmllint's path and files
validator.exec = 		xmllint --schema 
validator.file-prefix = ValidatorInput_
validator.path.schema = ${base-dir}/validator_sources/ContractSchema.xsd
validator.path.files = 	${tmp-dir}/


